# This workflow will wget Luke's files each night at 0 UTC and add them to this repository in the luke-jr branch
name: luke-jr

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  luke-jr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Configure git and checkout branch
      run: |
        git config --local user.email "0xb10c+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        # make copy of script to retain it after switching branches
        cp download-luke-jr-data.sh script.sh
        git checkout luke-jr
    - name: Download files
      run: ./script.sh
    - name: Commit changes
      run: |
        git add *.txt
        git commit -m "Auto updated luke-jr files: $(date)" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: luke-jr
